// Verifies that Rust greedy produces identical move sequences to C++ greedy
// when started from the same initial hands.
//
// The golden file was generated by `bin/export_greedy_games 200 42` (C++ with
// std::mt19937). Each line: hand0[13]  hand1[13]  num_moves  move_id...
//
// Greedy is fully deterministic given fixed hands, so this test proves the
// move generation, GreedyEval ordering, and move encoding are bit-for-bit
// identical between C++ and Rust.

use big2_core::{Game, Move};
use big2_players::{player::AnyPlayer, Player};
use big2_players::greedy::GreedyStrategy;
use big2_simulation::simulator::play_game;

fn parse_golden(line: &str) -> ([u8; 13], [u8; 13], Vec<usize>) {
    let mut parts = line.split_whitespace();
    let mut h0 = [0u8; 13];
    let mut h1 = [0u8; 13];
    for x in &mut h0 { *x = parts.next().unwrap().parse().unwrap(); }
    for x in &mut h1 { *x = parts.next().unwrap().parse().unwrap(); }
    let n: usize = parts.next().unwrap().parse().unwrap();
    let moves: Vec<usize> = parts.take(n).map(|s| s.parse().unwrap()).collect();
    assert_eq!(moves.len(), n);
    (h0, h1, moves)
}

#[test]
fn greedy_exact_match_vs_cpp() {
    let golden = include_str!("greedy_golden.txt");
    let mut failures = 0;

    for (game_idx, line) in golden.lines().enumerate() {
        let (h0, h1, expected_moves) = parse_golden(line);

        let game = Game::from_state(h0, h1, [0u8; 13], Move::PASS, 0);
        let mut p0: Box<dyn AnyPlayer> = Box::new(Player::new(GreedyStrategy));
        let mut p1: Box<dyn AnyPlayer> = Box::new(Player::new(GreedyStrategy));
        let record = play_game(&game, p0.as_mut(), p1.as_mut());

        let rust_moves: Vec<usize> = record.turns.iter()
            .map(|t| t.mv.encode())
            .collect();

        if rust_moves != expected_moves {
            eprintln!(
                "MISMATCH game {}: expected {} moves, got {}",
                game_idx, expected_moves.len(), rust_moves.len()
            );
            let min_len = rust_moves.len().min(expected_moves.len());
            for i in 0..min_len {
                if rust_moves[i] != expected_moves[i] {
                    eprintln!("  first diff at turn {}: rust={} cpp={}", i, rust_moves[i], expected_moves[i]);
                    break;
                }
            }
            failures += 1;
        }
    }

    assert_eq!(failures, 0, "{} games had mismatched move sequences", failures);
}
